apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        {{- if .Values.metrics }}
        {{- if .Values.metrics.prometheus }}
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.metrics.prometheus.port | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: user-settings
          configMap:
            # Provide the   name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ .Release.Name }}-user-settings
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-admin-secret
                  key: password
          {{- with .Values.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: {{ .period }}
          {{- end }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: {{ .period }}
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: user-settings
              mountPath: /home/clayman/.local/share/code-server/User
