apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-admin-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  password: {{ default (randAlphaNum 16) .Values.adminSecret | b64enc | quote }}
